# Generated by Django 3.2.18 on 2023-04-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230425_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, help_text='Designates whether the user is a student', verbose_name='student'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text='Designates whether the user is a teacher', verbose_name='teacher'),
        ),
    ]
