# Generated by Django 3.2.18 on 2023-04-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230425_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
