# Generated by Django 3.2.18 on 2023-04-25 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('establishment', models.CharField(max_length=255)),
                ('project_type', models.CharField(choices=[('un diplôme - une startup', 'un diplôme - une startup'), ('Un diplôme - Un Brevet', 'Un diplôme - Un Brevet')], max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('On Hold', 'On Hold'), ('Rejected', 'Rejected')], default='On Hold', max_length=50)),
                ('deposition_date', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('trademark_name', models.CharField(blank=True, max_length=255, null=True)),
                ('scientific_product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('co_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_supervisor_user', to=settings.AUTH_USER_MODEL)),
                ('project_leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
