# Generated by Django 3.2.18 on 2023-04-23 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_leader',
        ),
        migrations.RemoveField(
            model_name='project',
            name='supervisors',
        ),
        migrations.RemoveField(
            model_name='student',
            name='project',
        ),
        migrations.RemoveField(
            model_name='student',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
