# Generated by Django 3.2.19 on 2023-05-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_rename_membres_validationcommittee_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='num_inscription',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
